# Generated by Django 2.0 on 2017-12-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='state',
            name='threshold',
        ),
        migrations.AddField(
            model_name='state',
            name='using_setting',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(default='on', max_length=10),
        ),
    ]
