# Generated by Django 2.0 on 2017-12-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_auto_20171217_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='cur_humid',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='state',
            name='cur_temp',
            field=models.IntegerField(default=-1),
        ),
    ]
