# Generated by Django 2.0 on 2017-12-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_auto_20171218_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='cur_humid',
            field=models.IntegerField(default=-100),
        ),
        migrations.AlterField(
            model_name='state',
            name='cur_temp',
            field=models.IntegerField(default=-100),
        ),
    ]
