# Generated by Django 2.0 on 2017-12-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_auto_20171218_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='auto',
            field=models.BooleanField(default=True),
        ),
    ]
