# Generated by Django 2.0 on 2017-12-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_auto_20171218_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='manual_setting',
            new_name='manual',
        ),
    ]
