# Generated by Django 2.0 on 2017-12-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_auto_20171218_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='cur_humid',
            new_name='humid',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='cur_temp',
            new_name='temp',
        ),
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(default='on', max_length=100),
        ),
    ]
