# Generated by Django 2.0 on 2017-12-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_auto_20171219_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='humid_threshold',
            new_name='min_temp',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='temp_threshold',
        ),
        migrations.AddField(
            model_name='setting',
            name='max_humid',
            field=models.IntegerField(default=55),
        ),
        migrations.AddField(
            model_name='setting',
            name='max_temp',
            field=models.IntegerField(default=32),
        ),
        migrations.AddField(
            model_name='setting',
            name='min_humid',
            field=models.IntegerField(default=35),
        ),
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.IntegerField(default='10'),
        ),
    ]
