# Generated by Django 2.0 on 2017-12-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0012_auto_20171220_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='degree',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='max_temp',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='setting',
            name='min_temp',
            field=models.IntegerField(default=20),
        ),
    ]
